export const getContentTypeResponse = {
  sys: {
    space: { sys: { type: 'Link', linkType: 'Space', id: 'tctsmza39jg6' } },
    id: 'testTopic',
    type: 'ContentType',
    createdAt: '2021-08-06T16:53:44.571Z',
    updatedAt: '2021-08-08T19:28:59.973Z',
    environment: {
      sys: { id: 'master', type: 'Link', linkType: 'Environment' },
    },
    publishedVersion: 19,
    publishedAt: '2021-08-08T19:28:59.973Z',
    firstPublishedAt: '2021-08-06T16:53:45.059Z',
    createdBy: {
      sys: { type: 'Link', linkType: 'User', id: '5TOHdotj5KMHTHKvucd6zZ' },
    },
    updatedBy: {
      sys: { type: 'Link', linkType: 'User', id: '5TOHdotj5KMHTHKvucd6zZ' },
    },
    publishedCounter: 10,
    version: 20,
    publishedBy: {
      sys: { type: 'Link', linkType: 'User', id: '5TOHdotj5KMHTHKvucd6zZ' },
    },
  },
  displayField: 'heading',
  name: 'testTopic',
  description: 'Topic model, a heading, an abstract and a call to action',
  fields: [
    {
      id: 'abstract',
      name: 'Abstract',
      type: 'Symbol',
      localized: false,
      required: false,
      validations: [
        { size: { max: 155, min: 0 } },
        { size: { max: 155, min: 0 } },
        { size: { max: 155, min: 0 } },
        { size: { max: 155, min: 0 } },
        { size: { max: 155, min: 0 } },
      ],
      disabled: false,
      omitted: false,
    },
    {
      id: 'actions',
      name: 'Actions',
      type: 'Array',
      localized: false,
      required: false,
      validations: [],
      disabled: false,
      omitted: false,
      items: {
        type: 'Link',
        validations: [
          { linkContentType: ['testAction'] },
          { linkContentType: ['testAction'] },
          { linkContentType: ['testAction'] },
          { linkContentType: ['testAction'] },
          { linkContentType: ['testAction'] },
        ],
        linkType: 'Entry',
      },
    },
    {
      id: 'heading',
      name: 'Heading',
      type: 'Symbol',
      localized: false,
      required: false,
      validations: [],
      disabled: false,
      omitted: false,
    },
    {
      id: 'icon',
      name: 'Icon',
      type: 'Symbol',
      localized: false,
      required: false,
      validations: [],
      disabled: false,
      omitted: false,
    },
    {
      id: 'media',
      name: 'Media',
      type: 'Array',
      localized: false,
      required: false,
      validations: [],
      disabled: false,
      omitted: false,
      items: { type: 'Link', validations: [], linkType: 'Asset' },
    },
    {
      id: 'poster',
      name: 'Poster',
      type: 'Link',
      localized: false,
      required: false,
      validations: [],
      disabled: false,
      omitted: false,
      linkType: 'Asset',
    },
  ],
}
