export const getContentTypesResponse = {
  sys: { type: 'Array' },
  total: 11,
  skip: 0,
  limit: 100,
  items: [
    {
      sys: {
        space: {
          sys: { type: 'Link', linkType: 'Space', id: 'tctsmza39jg6' },
        },
        id: 'testTopic',
        type: 'ContentType',
        createdAt: '2021-08-06T16:53:44.571Z',
        updatedAt: '2021-08-08T19:28:59.973Z',
        environment: {
          sys: { id: 'master', type: 'Link', linkType: 'Environment' },
        },
        publishedVersion: 19,
        publishedAt: '2021-08-08T19:28:59.973Z',
        firstPublishedAt: '2021-08-06T16:53:45.059Z',
        createdBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
        updatedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
        publishedCounter: 10,
        version: 20,
        publishedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
      },
      displayField: 'heading',
      name: 'testTopic',
      description: 'Topic model, a heading, an abstract and a call to action',
      fields: [
        {
          id: 'abstract',
          name: 'Abstract',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [
            { size: { max: 155, min: 0 } },
            { size: { max: 155, min: 0 } },
            { size: { max: 155, min: 0 } },
            { size: { max: 155, min: 0 } },
            { size: { max: 155, min: 0 } },
          ],
          disabled: false,
          omitted: false,
        },
        {
          id: 'actions',
          name: 'Actions',
          type: 'Array',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
          items: {
            type: 'Link',
            validations: [
              { linkContentType: ['testAction'] },
              { linkContentType: ['testAction'] },
              { linkContentType: ['testAction'] },
              { linkContentType: ['testAction'] },
              { linkContentType: ['testAction'] },
            ],
            linkType: 'Entry',
          },
        },
        {
          id: 'heading',
          name: 'Heading',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'icon',
          name: 'Icon',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'media',
          name: 'Media',
          type: 'Array',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
          items: { type: 'Link', validations: [], linkType: 'Asset' },
        },
        {
          id: 'poster',
          name: 'Poster',
          type: 'Link',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
          linkType: 'Asset',
        },
      ],
    },
    {
      sys: {
        space: {
          sys: { type: 'Link', linkType: 'Space', id: 'tctsmza39jg6' },
        },
        id: 'testAction',
        type: 'ContentType',
        createdAt: '2021-08-05T21:24:19.855Z',
        updatedAt: '2021-08-08T19:28:56.882Z',
        environment: {
          sys: { id: 'master', type: 'Link', linkType: 'Environment' },
        },
        publishedVersion: 46,
        publishedAt: '2021-08-08T19:28:56.882Z',
        firstPublishedAt: '2021-08-05T21:24:23.900Z',
        createdBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
        updatedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
        publishedCounter: 21,
        version: 47,
        publishedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
      },
      displayField: 'heading',
      name: 'testAction',
      description: null,
      fields: [
        {
          id: 'anchor',
          name: 'Anchor',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'description',
          name: 'Description',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'eventId',
          name: 'Event id',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'heading',
          name: 'Heading',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'query',
          name: 'Query',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'url',
          name: 'Url',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
      ],
    },
    {
      sys: {
        space: {
          sys: { type: 'Link', linkType: 'Space', id: 'tctsmza39jg6' },
        },
        id: 'navigationSection',
        type: 'ContentType',
        createdAt: '2021-08-05T21:24:18.246Z',
        updatedAt: '2021-08-05T21:24:23.551Z',
        environment: {
          sys: { id: 'master', type: 'Link', linkType: 'Environment' },
        },
        publishedVersion: 1,
        publishedAt: '2021-08-05T21:24:23.551Z',
        firstPublishedAt: '2021-08-05T21:24:23.551Z',
        createdBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
        updatedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
        publishedCounter: 1,
        version: 2,
        publishedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
      },
      displayField: 'title',
      name: 'navigationSection',
      description: 'navigationSection',
      fields: [
        {
          id: 'title',
          name: 'Title',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'logo',
          name: 'Logo',
          type: 'Link',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
          linkType: 'Asset',
        },
        {
          id: 'logoAction',
          name: 'Logo action',
          type: 'Link',
          localized: false,
          required: false,
          validations: [{ linkContentType: ['action'] }],
          disabled: false,
          omitted: false,
          linkType: 'Entry',
        },
        {
          id: 'header',
          name: 'Header',
          type: 'Array',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
          items: {
            type: 'Link',
            validations: [{ linkContentType: ['navigationSegment'] }],
            linkType: 'Entry',
          },
        },
        {
          id: 'footer',
          name: 'Footer',
          type: 'Array',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
          items: {
            type: 'Link',
            validations: [{ linkContentType: ['navigationSegment'] }],
            linkType: 'Entry',
          },
        },
        {
          id: 'social',
          name: 'Social',
          type: 'Link',
          localized: false,
          required: false,
          validations: [{ linkContentType: ['navigationSegment'] }],
          disabled: false,
          omitted: false,
          linkType: 'Entry',
        },
        {
          id: 'actions',
          name: 'Actions',
          type: 'Link',
          localized: false,
          required: false,
          validations: [{ linkContentType: ['navigationSegment'] }],
          disabled: false,
          omitted: false,
          linkType: 'Entry',
        },
        {
          id: 'legal',
          name: 'Legal',
          type: 'Link',
          localized: false,
          required: false,
          validations: [{ linkContentType: ['navigationSegment'] }],
          disabled: false,
          omitted: false,
          linkType: 'Entry',
        },
        {
          id: 'information',
          name: 'Information',
          type: 'Array',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
          items: {
            type: 'Link',
            validations: [{ linkContentType: ['navigationSegment'] }],
            linkType: 'Entry',
          },
        },
        {
          id: 'sitemap',
          name: 'Sitemap',
          type: 'Array',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
          items: {
            type: 'Link',
            validations: [{ linkContentType: ['navigationSegment'] }],
            linkType: 'Entry',
          },
        },
      ],
    },
    {
      sys: {
        space: {
          sys: { type: 'Link', linkType: 'Space', id: 'tctsmza39jg6' },
        },
        id: 'topicSection',
        type: 'ContentType',
        createdAt: '2021-08-05T21:24:18.088Z',
        updatedAt: '2021-08-05T21:24:22.940Z',
        environment: {
          sys: { id: 'master', type: 'Link', linkType: 'Environment' },
        },
        publishedVersion: 1,
        publishedAt: '2021-08-05T21:24:22.940Z',
        firstPublishedAt: '2021-08-05T21:24:22.940Z',
        createdBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
        updatedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
        publishedCounter: 1,
        version: 2,
        publishedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
      },
      displayField: 'title',
      name: 'topicSection',
      description: 'Topic section',
      fields: [
        {
          id: 'title',
          name: 'Titel binnen Contentful',
          type: 'Symbol',
          localized: false,
          required: true,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'variant',
          name: 'Sectie weergave',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [
            {
              in: [
                'block',
                'card',
                'divider',
                'featured',
                'gallery',
                'headline',
                'hero',
                'image',
                'quote',
                'showcase',
                'video',
              ],
            },
          ],
          disabled: false,
          omitted: false,
        },
        {
          id: 'topics',
          name: 'Sectie onderwerpen',
          type: 'Array',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
          items: {
            type: 'Link',
            validations: [{ linkContentType: ['topic'] }],
            linkType: 'Entry',
          },
        },
        {
          id: 'hideIcon',
          name: 'Hide icon',
          type: 'Boolean',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'hideMedia',
          name: 'Hide media',
          type: 'Boolean',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'hideHeading',
          name: 'Hide heading',
          type: 'Boolean',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'hideAbstract',
          name: 'Hide abstract',
          type: 'Boolean',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'hideAction',
          name: 'Hide action',
          type: 'Boolean',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'reversedOrder',
          name: 'Reversed order',
          type: 'Boolean',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'eventId',
          name: 'Event id',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [{ unique: true }],
          disabled: false,
          omitted: false,
        },
        {
          id: 'theme',
          name: 'Sectie thema',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [{ in: ['glacierLight', 'glacierDark'] }],
          disabled: false,
          omitted: false,
        },
        {
          id: 'modelVersion',
          name: '1.0.0',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: true,
          omitted: false,
        },
      ],
    },
    {
      sys: {
        space: {
          sys: { type: 'Link', linkType: 'Space', id: 'tctsmza39jg6' },
        },
        id: 'topic',
        type: 'ContentType',
        createdAt: '2021-08-05T21:24:20.096Z',
        updatedAt: '2021-08-05T21:24:22.602Z',
        environment: {
          sys: { id: 'master', type: 'Link', linkType: 'Environment' },
        },
        publishedVersion: 1,
        publishedAt: '2021-08-05T21:24:22.602Z',
        firstPublishedAt: '2021-08-05T21:24:22.602Z',
        createdBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
        updatedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
        publishedCounter: 1,
        version: 2,
        publishedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
      },
      displayField: 'title',
      name: 'topic',
      description: 'Topic',
      fields: [
        {
          id: 'title',
          name: 'Titel binnen Contentful',
          type: 'Symbol',
          localized: false,
          required: true,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'heading',
          name: 'Onderwerp titel',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'abstract',
          name: 'Onderwerp tekst',
          type: 'Text',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'media',
          name: 'Onderwerp afbeelding',
          type: 'Array',
          localized: false,
          required: false,
          validations: [{ size: { min: 1, max: 4 } }],
          disabled: false,
          omitted: false,
          items: { type: 'Link', validations: [], linkType: 'Asset' },
        },
        {
          id: 'icon',
          name: 'Onderwerp icoon',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [
            {
              in: [
                'activity',
                'airplay',
                'alert-circle',
                'alert-octagon',
                'alert-triangle',
                'align-center',
                'align-justify',
                'align-left',
                'align-right',
                'anchor',
                'aperture',
                'archive',
                'arrow-down-circle',
                'arrow-down-left',
                'arrow-down-right',
                'arrow-down',
                'arrow-left-circle',
                'arrow-left',
                'arrow-right-circle',
                'arrow-right',
                'arrow-up-circle',
                'arrow-up-left',
                'arrow-up-right',
                'arrow-up',
                'at-sign',
                'award',
                'bar-chart-2',
                'bar-chart',
                'battery-charging',
                'battery',
                'bell-off',
                'bell',
                'bluetooth',
                'bold',
                'book-open',
                'book',
                'bookmark',
                'box',
                'briefcase',
                'calendar',
                'camera-off',
                'camera',
                'cast',
                'check-circle',
                'check-square',
                'check',
                'chevron-down',
                'chevron-left',
                'chevron-right',
                'chevron-up',
                'chevrons-down',
                'chevrons-left',
                'chevrons-right',
                'chevrons-up',
                'chrome',
                'circle',
                'clipboard',
                'clock',
                'cloud-drizzle',
                'cloud-lightning',
                'cloud-off',
                'cloud-rain',
                'cloud-snow',
                'cloud',
                'code',
                'codepen',
                'codesandbox',
                'coffee',
                'columns',
                'command',
                'compass',
                'copy',
                'corner-down-left',
                'corner-down-right',
                'corner-left-down',
                'corner-left-up',
                'corner-right-down',
                'corner-right-up',
                'corner-up-left',
                'corner-up-right',
                'cpu',
                'credit-card',
                'crop',
                'crosshair',
                'database',
                'delete',
                'disc',
                'dollar-sign',
                'download-cloud',
                'download',
                'droplet',
                'edit-2',
                'edit-3',
                'edit',
                'external-link',
                'eye-off',
                'eye',
                'facebook',
                'fast-forward',
                'feather',
                'figma',
                'file-minus',
                'file-plus',
                'file-text',
                'file',
                'film',
                'filter',
                'flag',
                'folder-minus',
                'folder-plus',
                'folder',
                'framer',
                'frown',
                'gift',
                'git-branch',
                'git-commit',
                'git-merge',
                'git-pull-request',
                'github',
                'gitlab',
                'globe',
                'grid',
                'hard-drive',
                'hash',
                'headphones',
                'heart',
                'help-circle',
                'hexagon',
                'home',
                'image',
                'inbox',
                'info',
                'instagram',
                'italic',
                'key',
                'layers',
                'layout',
                'life-buoy',
                'link-2',
                'link',
                'linkedin',
                'list',
                'loader',
                'lock',
                'log-in',
                'log-out',
                'mail',
                'map-pin',
                'map',
                'maximize-2',
                'maximize',
                'meh',
                'menu',
                'message-circle',
                'message-square',
                'mic-off',
                'mic',
                'minimize-2',
                'minimize',
                'minus-circle',
                'minus-square',
                'minus',
                'monitor',
                'moon',
                'more-horizontal',
                'more-vertical',
                'mouse-pointer',
                'move',
                'music',
                'navigation-2',
                'navigation',
                'octagon',
                'package',
                'paperclip',
                'pause-circle',
                'pause',
                'pen-tool',
                'percent',
                'phone-call',
                'phone-forwarded',
                'phone-incoming',
                'phone-missed',
                'phone-off',
                'phone-outgoing',
                'phone',
                'pie-chart',
                'play-circle',
                'play',
                'plus-circle',
                'plus-square',
                'plus',
                'pocket',
                'power',
                'printer',
                'radio',
                'refresh-ccw',
                'refresh-cw',
                'repeat',
                'rewind',
                'rotate-ccw',
                'rotate-cw',
                'rss',
                'save',
                'scissors',
                'search',
                'send',
                'server',
                'settings',
                'share-2',
                'share',
                'shield-off',
                'shield',
                'shopping-bag',
                'shopping-cart',
                'shuffle',
                'sidebar',
                'skip-back',
                'skip-forward',
                'slack',
                'slash',
                'sliders',
                'smartphone',
                'smile',
                'speaker',
                'square',
                'star',
                'stop-circle',
                'sun',
                'sunrise',
                'sunset',
                'tablet',
                'tag',
                'target',
                'terminal',
                'thermometer',
                'thumbs-down',
                'thumbs-up',
                'toggle-left',
                'toggle-right',
                'tool',
                'trash-2',
                'trash',
                'trello',
                'trending-down',
                'trending-up',
                'triangle',
                'truck',
                'tv',
                'twitch',
                'twitter',
                'type',
                'umbrella',
                'underline',
                'unlock',
                'upload-cloud',
                'upload',
                'user-check',
                'user-minus',
                'user-plus',
                'user-x',
                'user',
                'users',
                'video-off',
                'video',
                'voicemail',
                'volume-1',
                'volume-2',
                'volume-x',
                'volume',
                'watch',
                'wifi-off',
                'wifi',
                'wind',
                'x-circle',
                'x-octagon',
                'x-square',
                'x',
                'youtube',
                'zap-off',
                'zap',
                'zoom-in',
                'zoom-out',
              ],
            },
          ],
          disabled: false,
          omitted: false,
        },
        {
          id: 'actions',
          name: 'Onderwerp acties',
          type: 'Array',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
          items: {
            type: 'Link',
            validations: [{ linkContentType: ['action'] }],
            linkType: 'Entry',
          },
        },
        {
          id: 'poster',
          name: 'Poster',
          type: 'Link',
          localized: false,
          required: false,
          validations: [{ linkMimetypeGroup: ['image'] }],
          disabled: false,
          omitted: false,
          linkType: 'Asset',
        },
        {
          id: 'mediaEmbed',
          name: 'Media embed',
          type: 'Link',
          localized: false,
          required: false,
          validations: [{ linkContentType: ['embed'] }],
          disabled: false,
          omitted: false,
          linkType: 'Entry',
        },
        {
          id: 'modelVersion',
          name: '1.0.0',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: true,
          omitted: false,
        },
      ],
    },
    {
      sys: {
        space: {
          sys: { type: 'Link', linkType: 'Space', id: 'tctsmza39jg6' },
        },
        id: 'textSection',
        type: 'ContentType',
        createdAt: '2021-08-05T21:24:17.604Z',
        updatedAt: '2021-08-05T21:24:22.296Z',
        environment: {
          sys: { id: 'master', type: 'Link', linkType: 'Environment' },
        },
        publishedVersion: 1,
        publishedAt: '2021-08-05T21:24:22.296Z',
        firstPublishedAt: '2021-08-05T21:24:22.296Z',
        createdBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
        updatedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
        publishedCounter: 1,
        version: 2,
        publishedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
      },
      displayField: 'title',
      name: 'textSection',
      description: 'Text section',
      fields: [
        {
          id: 'title',
          name: 'Titel binnen Contentful',
          type: 'Symbol',
          localized: false,
          required: true,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'variant',
          name: 'Variant',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [{ in: ['text'] }],
          disabled: false,
          omitted: false,
        },
        {
          id: 'text',
          name: 'Tekst',
          type: 'RichText',
          localized: false,
          required: true,
          validations: [
            {
              enabledMarks: ['bold', 'italic', 'underline', 'code'],
              message:
                'Only bold, italic, underline, and code marks are allowed',
            },
            {
              nodes: {
                'embedded-entry-block': [
                  { linkContentType: ['embed', 'topicSection'] },
                ],
                'embedded-entry-inline': [
                  {
                    linkContentType: ['embed', 'topicSection'],
                    message: null,
                  },
                ],
              },
            },
          ],
          disabled: false,
          omitted: false,
        },
        {
          id: 'eventId',
          name: 'Event id',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [{ unique: true }],
          disabled: false,
          omitted: false,
        },
        {
          id: 'modelVersion',
          name: '1.0.0',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: true,
          omitted: false,
        },
      ],
    },
    {
      sys: {
        space: {
          sys: { type: 'Link', linkType: 'Space', id: 'tctsmza39jg6' },
        },
        id: 'navigationSegment',
        type: 'ContentType',
        createdAt: '2021-08-05T21:24:17.555Z',
        updatedAt: '2021-08-05T21:24:21.726Z',
        environment: {
          sys: { id: 'master', type: 'Link', linkType: 'Environment' },
        },
        publishedVersion: 1,
        publishedAt: '2021-08-05T21:24:21.726Z',
        firstPublishedAt: '2021-08-05T21:24:21.726Z',
        createdBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
        updatedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
        publishedCounter: 1,
        version: 2,
        publishedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
      },
      displayField: 'title',
      name: 'navigationSegment',
      description: 'Navigation segment',
      fields: [
        {
          id: 'title',
          name: 'Titel binnen Contentful',
          type: 'Symbol',
          localized: false,
          required: true,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'heading',
          name: 'Navigatiesegment titel',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'abstract',
          name: 'Segment tekst',
          type: 'Text',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'actions',
          name: 'Acties voor dit segment',
          type: 'Array',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
          items: {
            type: 'Link',
            validations: [{ linkContentType: ['action'] }],
            linkType: 'Entry',
          },
        },
        {
          id: 'modelVersion',
          name: '1.0.0',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: true,
          omitted: false,
        },
      ],
    },
    {
      sys: {
        space: {
          sys: { type: 'Link', linkType: 'Space', id: 'tctsmza39jg6' },
        },
        id: 'page',
        type: 'ContentType',
        createdAt: '2021-08-05T21:24:17.570Z',
        updatedAt: '2021-08-05T21:24:21.390Z',
        environment: {
          sys: { id: 'master', type: 'Link', linkType: 'Environment' },
        },
        publishedVersion: 1,
        publishedAt: '2021-08-05T21:24:21.390Z',
        firstPublishedAt: '2021-08-05T21:24:21.390Z',
        createdBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
        updatedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
        publishedCounter: 1,
        version: 2,
        publishedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
      },
      displayField: 'title',
      name: 'page',
      description: 'Page',
      fields: [
        {
          id: 'title',
          name: 'Titel binnen Contentful',
          type: 'Symbol',
          localized: false,
          required: true,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'path',
          name: 'Pagina URL',
          type: 'Symbol',
          localized: false,
          required: true,
          validations: [
            {
              message:
                'Please use a valid path: /this/is/a/valid/path/with/:slug',
              regexp: {
                pattern: '^\\/[a-z0-9:\\._/~%\\-\\+&\\#\\?!=\\(\\)@]*$',
              },
            },
            { unique: true },
          ],
          disabled: false,
          omitted: false,
        },
        {
          id: 'sections',
          name: 'Paginasecties',
          type: 'Array',
          localized: false,
          required: true,
          validations: [],
          disabled: false,
          omitted: false,
          items: {
            type: 'Link',
            validations: [
              {
                linkContentType: [
                  'navigationSection',
                  'tableSection',
                  'textSection',
                  'topicSection',
                ],
              },
            ],
            linkType: 'Entry',
          },
        },
        {
          id: 'theme',
          name: 'Paginathema',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [{ in: ['glacierLight', 'glacierDark'] }],
          disabled: false,
          omitted: false,
        },
        {
          id: 'seoTitle',
          name: 'SEO titel',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'seoDescription',
          name: 'SEO omschrijving',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [{ size: { max: 155, min: 0 } }],
          disabled: false,
          omitted: false,
        },
        {
          id: 'seoImage',
          name: 'SEO afbeelding',
          type: 'Link',
          localized: false,
          required: false,
          validations: [{ linkMimetypeGroup: ['image'] }],
          disabled: false,
          omitted: false,
          linkType: 'Asset',
        },
        {
          id: 'seoKeywords',
          name: 'Seo keywords',
          type: 'Array',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
          items: { type: 'Symbol', validations: [] },
        },
        {
          id: 'modelVersion',
          name: '1.0.0',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: true,
          omitted: false,
        },
      ],
    },
    {
      sys: {
        space: {
          sys: { type: 'Link', linkType: 'Space', id: 'tctsmza39jg6' },
        },
        id: 'globals',
        type: 'ContentType',
        createdAt: '2021-08-05T21:24:17.577Z',
        updatedAt: '2021-08-05T21:24:21.013Z',
        environment: {
          sys: { id: 'master', type: 'Link', linkType: 'Environment' },
        },
        publishedVersion: 1,
        publishedAt: '2021-08-05T21:24:21.013Z',
        firstPublishedAt: '2021-08-05T21:24:21.013Z',
        createdBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
        updatedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
        publishedCounter: 1,
        version: 2,
        publishedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
      },
      displayField: 'title',
      name: 'globals',
      description: 'Globals',
      fields: [
        {
          id: 'title',
          name: 'Titel binnen Contentful',
          type: 'Symbol',
          localized: false,
          required: true,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'siteAuthor',
          name: 'Site auteur',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'siteDescription',
          name: 'Site omschrijving',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'siteHeading',
          name: 'Site titel',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'siteKeywords',
          name: 'Site sleutelwoorden',
          type: 'Array',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
          items: { type: 'Symbol', validations: [] },
        },
        {
          id: 'siteImage',
          name: 'Site image',
          type: 'Link',
          localized: false,
          required: false,
          validations: [{ linkMimetypeGroup: ['image'] }],
          disabled: false,
          omitted: false,
          linkType: 'Asset',
        },
        {
          id: 'siteEmbeds',
          name: 'Site embeds',
          type: 'Array',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
          items: {
            type: 'Link',
            validations: [{ linkContentType: ['embed'] }],
            linkType: 'Entry',
          },
        },
        {
          id: 'skipToContentHeading',
          name: 'Direct naar content',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'modelVersion',
          name: '1.0.0',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: true,
          omitted: false,
        },
      ],
    },
    {
      sys: {
        space: {
          sys: { type: 'Link', linkType: 'Space', id: 'tctsmza39jg6' },
        },
        id: 'embed',
        type: 'ContentType',
        createdAt: '2021-08-05T21:24:17.547Z',
        updatedAt: '2021-08-05T21:24:20.715Z',
        environment: {
          sys: { id: 'master', type: 'Link', linkType: 'Environment' },
        },
        publishedVersion: 1,
        publishedAt: '2021-08-05T21:24:20.715Z',
        firstPublishedAt: '2021-08-05T21:24:20.715Z',
        createdBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
        updatedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
        publishedCounter: 1,
        version: 2,
        publishedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
      },
      displayField: 'title',
      name: 'embed',
      description: 'Embed',
      fields: [
        {
          id: 'title',
          name: 'Titel binnen Contentful',
          type: 'Symbol',
          localized: false,
          required: true,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'code',
          name: 'Code',
          type: 'Text',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'type',
          name: 'Type',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [
            {
              in: [
                'html',
                'js-action',
                'js-app',
                'js-page-section',
                'js-page',
                'youtube',
              ],
            },
          ],
          disabled: false,
          omitted: false,
        },
        {
          id: 'modelVersion',
          name: '1.0.0',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: true,
          omitted: false,
        },
      ],
    },
    {
      sys: {
        space: {
          sys: { type: 'Link', linkType: 'Space', id: 'tctsmza39jg6' },
        },
        id: 'action',
        type: 'ContentType',
        createdAt: '2021-08-05T21:24:17.564Z',
        updatedAt: '2021-08-05T21:24:20.359Z',
        environment: {
          sys: { id: 'master', type: 'Link', linkType: 'Environment' },
        },
        publishedVersion: 1,
        publishedAt: '2021-08-05T21:24:20.359Z',
        firstPublishedAt: '2021-08-05T21:24:20.359Z',
        createdBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
        updatedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
        publishedCounter: 1,
        version: 2,
        publishedBy: {
          sys: {
            type: 'Link',
            linkType: 'User',
            id: '5TOHdotj5KMHTHKvucd6zZ',
          },
        },
      },
      displayField: 'title',
      name: 'action',
      description: 'Action',
      fields: [
        {
          id: 'title',
          name: 'Titel binnen Contentful',
          type: 'Symbol',
          localized: false,
          required: true,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'heading',
          name: 'Actie naam',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'description',
          name: 'Actie omschrijving',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'icon',
          name: 'Icon',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [
            {
              in: [
                'activity',
                'airplay',
                'alert-circle',
                'alert-octagon',
                'alert-triangle',
                'align-center',
                'align-justify',
                'align-left',
                'align-right',
                'anchor',
                'aperture',
                'archive',
                'arrow-down-circle',
                'arrow-down-left',
                'arrow-down-right',
                'arrow-down',
                'arrow-left-circle',
                'arrow-left',
                'arrow-right-circle',
                'arrow-right',
                'arrow-up-circle',
                'arrow-up-left',
                'arrow-up-right',
                'arrow-up',
                'at-sign',
                'award',
                'bar-chart-2',
                'bar-chart',
                'battery-charging',
                'battery',
                'bell-off',
                'bell',
                'bluetooth',
                'bold',
                'book-open',
                'book',
                'bookmark',
                'box',
                'briefcase',
                'calendar',
                'camera-off',
                'camera',
                'cast',
                'check-circle',
                'check-square',
                'check',
                'chevron-down',
                'chevron-left',
                'chevron-right',
                'chevron-up',
                'chevrons-down',
                'chevrons-left',
                'chevrons-right',
                'chevrons-up',
                'chrome',
                'circle',
                'clipboard',
                'clock',
                'cloud-drizzle',
                'cloud-lightning',
                'cloud-off',
                'cloud-rain',
                'cloud-snow',
                'cloud',
                'code',
                'codepen',
                'codesandbox',
                'coffee',
                'columns',
                'command',
                'compass',
                'copy',
                'corner-down-left',
                'corner-down-right',
                'corner-left-down',
                'corner-left-up',
                'corner-right-down',
                'corner-right-up',
                'corner-up-left',
                'corner-up-right',
                'cpu',
                'credit-card',
                'crop',
                'crosshair',
                'database',
                'delete',
                'disc',
                'dollar-sign',
                'download-cloud',
                'download',
                'droplet',
                'edit-2',
                'edit-3',
                'edit',
                'external-link',
                'eye-off',
                'eye',
                'facebook',
                'fast-forward',
                'feather',
                'figma',
                'file-minus',
                'file-plus',
                'file-text',
                'file',
                'film',
                'filter',
                'flag',
                'folder-minus',
                'folder-plus',
                'folder',
                'framer',
                'frown',
                'gift',
                'git-branch',
                'git-commit',
                'git-merge',
                'git-pull-request',
                'gitlab',
                'globe',
                'grid',
                'hard-drive',
                'hash',
                'headphones',
                'heart',
                'help-circle',
                'hexagon',
                'home',
                'image',
                'inbox',
                'info',
                'instagram',
                'italic',
                'key',
                'layers',
                'layout',
                'life-buoy',
                'link-2',
                'link',
                'linkedin',
                'list',
                'loader',
                'lock',
                'log-in',
                'log-out',
                'mail',
                'map-pin',
                'map',
                'maximize-2',
                'maximize',
                'meh',
                'menu',
                'message-circle',
                'message-square',
                'mic-off',
                'mic',
                'minimize-2',
                'minimize',
                'minus-circle',
                'minus-square',
                'minus',
                'monitor',
                'moon',
                'more-horizontal',
                'more-vertical',
                'mouse-pointer',
                'move',
                'music',
                'navigation-2',
                'navigation',
                'octagon',
                'package',
                'paperclip',
                'pause-circle',
                'pause',
                'pen-tool',
                'percent',
                'phone-call',
                'phone-forwarded',
                'phone-incoming',
                'phone-missed',
                'phone-off',
                'phone-outgoing',
                'phone',
                'pie-chart',
                'play-circle',
                'play',
                'plus-circle',
                'plus-square',
                'plus',
                'pocket',
                'power',
                'printer',
                'radio',
                'refresh-ccw',
                'refresh-cw',
                'repeat',
                'rewind',
                'rotate-ccw',
                'rotate-cw',
                'rss',
                'save',
                'scissors',
                'search',
                'send',
                'server',
                'settings',
                'share-2',
                'share',
                'shield-off',
                'shield',
                'shopping-bag',
                'shopping-cart',
                'shuffle',
                'sidebar',
                'skip-back',
                'skip-forward',
                'slack',
                'slash',
                'sliders',
                'smartphone',
                'smile',
                'speaker',
                'square',
                'star',
                'stop-circle',
                'sun',
                'sunrise',
                'sunset',
                'tablet',
                'tag',
                'target',
                'terminal',
                'thermometer',
                'thumbs-down',
                'thumbs-up',
                'toggle-left',
                'toggle-right',
                'tool',
                'trash-2',
                'trash',
                'trello',
                'trending-down',
                'trending-up',
                'triangle',
                'truck',
                'tv',
                'twitch',
                'twitter',
                'type',
                'umbrella',
                'underline',
                'unlock',
                'upload-cloud',
                'upload',
                'user-check',
                'user-minus',
                'user-plus',
                'user-x',
                'user',
                'users',
                'video-off',
                'video',
                'voicemail',
                'volume-1',
                'volume-2',
                'volume-x',
                'volume',
                'watch',
                'wifi-off',
                'wifi',
                'wind',
                'x-circle',
                'x-octagon',
                'x-square',
                'x',
                'youtube',
                'zap-off',
                'zap',
                'zoom-in',
                'zoom-out',
                'Github',
              ],
            },
          ],
          disabled: false,
          omitted: false,
        },
        {
          id: 'page',
          name: 'Actie paginalink',
          type: 'Link',
          localized: false,
          required: false,
          validations: [{ linkContentType: ['page'] }],
          disabled: false,
          omitted: false,
          linkType: 'Entry',
        },
        {
          id: 'url',
          name: 'Actie URL',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [
            {
              message: 'Please use a valid url: https://this/is/a/valid/url',
              regexp: {
                pattern:
                  '^(ftp|http|https):\\/\\/(\\w+:{0,1}\\w*@)?(\\S+)(:[0-9]+)?(\\/|\\/([\\w#!:.?+=&%@!\\-/]))?$',
              },
            },
          ],
          disabled: false,
          omitted: false,
        },
        {
          id: 'anchor',
          name: 'Anchor',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'query',
          name: 'Query',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: false,
          omitted: false,
        },
        {
          id: 'eventId',
          name: 'Event id',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [{ unique: true }],
          disabled: false,
          omitted: false,
        },
        {
          id: 'modelVersion',
          name: '1.0.0',
          type: 'Symbol',
          localized: false,
          required: false,
          validations: [],
          disabled: true,
          omitted: false,
        },
      ],
    },
  ],
}
